# Funding options for LCP Specification
# If you'd like to support the development of LCP, consider sponsoring

github: [Turf-Tech]
# patreon: # Add Patreon username if available
# open_collective: # Add Open Collective project name if available
# custom: # Add custom funding links if needed
